#ifndef PID_SHOOT_SETTING_H
#define PID_SHOOT_SETTING_H

#include "struct_typedef.h"
#include "SentryAutoParameter.h"

// 摩擦轮
// 无力
fp32 AMMO_LEFT_SPEED_0MS[3] = {AMMO_LEFT_SPEED_0MS_KP, AMMO_LEFT_SPEED_0MS_KI, AMMO_LEFT_SPEED_0MS_KD};
fp32 AMMO_RIGHT_SPEED_0MS[3] = {AMMO_RIGHT_SPEED_0MS_KP, AMMO_RIGHT_SPEED_0MS_KI, AMMO_RIGHT_SPEED_0MS_KD};
// 30ms
fp32 AMMO_LEFT_SPEED_30MS[3] = {AMMO_LEFT_SPEED_30MS_KP, AMMO_LEFT_SPEED_30MS_KI, AMMO_LEFT_SPEED_30MS_KD};
fp32 AMMO_RIGHT_SPEED_30MS[3] = {AMMO_RIGHT_SPEED_30MS_KP, AMMO_RIGHT_SPEED_30MS_KI, AMMO_RIGHT_SPEED_30MS_KD};

// 拨盘
// 无力
fp32 ROTOR_NO_SPEED[3] = {ROTOR_NO_SPEED_KP, ROTOR_NO_SPEED_KI, ROTOR_NO_SPEED_KD};
fp32 ROTOR_YSE_SPEED[3] = {ROTOR_YSE_SPEED_KP, ROTOR_YSE_SPEED_KI, ROTOR_YSE_SPEED_KD};

// 列表
fp32 *AMMO_LEFT_LIST[] = {
    AMMO_LEFT_SPEED_0MS,
    AMMO_LEFT_SPEED_30MS,
    AMMO_LEFT_SPEED_30MS,
};

fp32 *AMMO_RIGHT_LIST[] = {
    AMMO_RIGHT_SPEED_0MS,
    AMMO_RIGHT_SPEED_30MS,
    AMMO_RIGHT_SPEED_30MS,
};

fp32 *ROTOR_LIST[] = {
    ROTOR_NO_SPEED,
    ROTOR_YSE_SPEED,
    ROTOR_YSE_SPEED,
    ROTOR_YSE_SPEED,
};

#endif